version: '2'

services:
    api:
        build: ./docker_resources/api
        volumes:
            - ./api:/var/www/api
        working_dir: /var/www/api
        ports:
            - "92:92"
        depends_on:
            - db_mysql
        networks:
            - cs

    vue:
        build: ./vue
        volumes:
            - ./vue:/app
        working_dir: /app
        ports:
            - "93:93"
            - "8080:8080"
        networks:
            - cs

    db_mysql:
        image: mysql:5.7
        volumes:
            - db_data_cs:/var/lib/mysql5.7
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "3308:3306"
        networks:
            - cs

networks:
    cs:
        driver: bridge

volumes:
    db_data_cs:
